name: test_env
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.1.1=0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py37hc8dfbb8_1
  - cloudpickle=1.3.0=py_0
  - cycler=0.10.0=py_2
  - cytoolz=0.10.1=py37h516909a_0
  - dask-core=2.12.0=py_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he1b5a44_2
  - ffmpeg=4.1.3=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.58.3=py37he00f558_1003
  - gmp=6.2.0=he1b5a44_2
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - imageio=2.8.0=py_0
  - intel-openmp=2020.0=166
  - jasper=1.900.1=h07fcdf6_1006
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py37h99015e2_1
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=15_mkl
  - libcblas=3.8.0=15_mkl
  - libclang=9.0.1=default_hde54327_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=15_mkl
  - liblapacke=3.8.0=15_mkl
  - libllvm9=9.0.1=hc9558a2_0
  - libopencv=4.2.0=py37_2
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc7e4089_4
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libwebp-base=1.1.0=2
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib-base=3.2.0=py37h250f245_1
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.2=he6710b0_0
  - nettle=3.4.1=h1bed415_1002
  - networkx=2.4=py_1
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py37h4f9e942_0
  - numpy-base=1.18.1=py37hde5b4d6_1
  - olefile=0.46=py_0
  - opencv=4.2.0=py37_2
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h7b6447c_4
  - pandas=1.0.1=py37h0573a6f_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.0.0=py37h718be6c_1
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h516909a_1003
  - plotly=4.5.4=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - py-opencv=4.2.0=py37h5ca1d4c_2
  - pyparsing=2.4.6=py_0
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37hc1659b7_0
  - qt=5.12.5=hd8c4c69_1
  - readline=7.0=h7b6447c_5
  - retrying=1.3.3=py37_2
  - scikit-image=0.16.2=py37hb3f55d8_0
  - scipy=1.4.1=py37h921218d_0
  - setuptools=46.0.0=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h8f50634_1
  - wheel=0.34.2=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h3b9ef0a_1
  - pip:
    - opencv-python==4.2.0.32
prefix: /home/yamanmy/anaconda3/envs/test_env

